workflows:
  # Claude Code Docker
  build-claude-code-docker:
    when:
      and:
        - << pipeline.parameters.build-claude-code-docker >>
    jobs:
      - docker/publish:
          dockerfile: Dockerfile
          path: docker
          image: otajisan/claude-code-docker
          docker_username: DOCKER_USERNAME
          docker_password: DOCKER_PASSWORD
          update_description: true
          tag: '${CIRCLE_SHA1}'
          filters:
            branches:
              #only:
              #  - main
              ignore:
                - main
