version: 2.1

jobs:
  claude-pr-analysis:
    docker:
      - image: otajisan/claude-code-docker:latest
    environment:
      - NODE_ENV: production

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Set environment variables for build
          command: |
            echo "export ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}" >> $BASH_ENV
            echo "export GITHUB_TOKEN=${GITHUB_TOKEN}" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: "Verify Environment Variables"
          command: |
            ./docker/scripts/verify-claude-code-token.sh
            ./docker/scripts/verify-github-token.sh
            echo "Claude Code version:"
            claude --version

      - run:
          name: "Generate PR Summary"
          command: |
            /claude-code-docker/scripts/generate-pr-summary.sh
            #./docker/scripts/generate-pr-summary.sh

      - run:
          name: "Automated Code Review"
          command: |
            #/claude-code-docker/scripts/automated-code-review.sh
            ./docker/scripts/automated-code-review.sh
