version: 2.1

jobs:
  claude-pr-analysis:
    docker:
      - image: otajisan/claude-code-docker:latest
    environment:
      - NODE_ENV: production

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: "Generate PR Summary"
          environment:
            ANTHROPIC_API_KEY: ANTHROPIC_API_KEY
            GITHUB_TOKEN: GITHUB_TOKEN
          command: |
            echo "Claude Code version:"
            claude --version

            echo "Environment variables check:"
            echo "ANTHROPIC_API_KEY is set: $([ -n "$ANTHROPIC_API_KEY" ] && echo "yes" || echo "no")"
            echo "GITHUB_TOKEN is set: $([ -n "$GITHUB_TOKEN" ] && echo "yes" || echo "no")"

            # execute the PR summary generation script
            pwd
            whoami
            ./docker/scripts/generate-pr-summary.sh
